url: ""

proofer:
  url_ignore:
    - "#"
    - "#comments"
    - !ruby/regexp '/https?:\/\/(www)?\.youtube\.com\/watch\?v=.*/i'
    - http://keegoid.com/404/
    - /edit/master/404.html
  check_html: true

github:
  url: "https://github.com/keegoid/keegoid.github.io/tree/dev"
  repository_nwo: "keegoid/keegoid.github.io"
  owner_url: "https://github.com/keegoid"
  repository_url: "https://github.com/keegoid/keegoid.github.io"
