# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Jekyll site for public writing on keegoid.com.

# Site settings
name: Keegan Mullaney
title: Keegoid
email: keeganmullaney@gmail.com
description: > # this means to ignore newlines
  The open source / public writing site for Keegan Mullaney.
author: keegoid
repository: keegoid/keegoid.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# frontmatter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      author: keegoid
      permalink: "/:categories/:title/"

# RDFa structured data
job_title: IT Administrator
employer: KM Authorized LLC
url: "http://keegoid.github.io"
location:
  city: Chongqing
  province: Chongqing
  country: China

# disqus:
#   shortname: 'keegoid'
#   count: 5
#   api_key: ""

# gravatar_id: ea353bd28baa1aefaefae736a19fcf2a
logo: /assets/img/headshot.jpg

twitter_username: keegoid
github_username:  keegoid

# plugin config
twitter:
  username: "@keegoid"
#ga_username: 'UA-18088627-1'
# google_site_verification:

# jekyll-mentions:
  # base_url: https://twitter.com

# Social metadata (JSON-LD)
# social:
#   name: Keegoid
#   - https://github.com/keegoid
#   - https://twitter.com/keegoid
#   - https://keybase.io/keegoid

# SEO YAML front matter
# title - The title of the post, page, or document
# description - A short description of the page's content
# image - Relative URL to an image associated with the post, page, or document (e.g., /assets/page-pic.jpg)
# author - Page-, post-, or document-specific author information

# build config
timezone: Asia/Shanghai
branch: master
permalink: pretty
rss_limit: 10
sass:
  sass_dir: _sass
  style: compressed

# GitHub Pages settings
github: [metadata]
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gist:
  noscript: false

# Jekyll plugins compatible with GitHub Pages
gems:
  - github-pages-health-check
  - jemoji
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

#files to exclude, array
exclude:
  - script
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - gulpfile.js
