#!/usr/bin/env bash

set -e # halt script on error

title() {
  echo
  echo " --------------------------  $1"
  echo
}

script/branding

#1
title "CHECK MARKDOWN"
script/remark

#2
title "CHECK SITE"
if "$CI"; then
  JEKYLL_GITHUB_TOKEN DISABLE_WHITELIST=true bundle exec rake
else
  JEKYLL_GITHUB_TOKEN="$(cat ~/.token)" DISABLE_WHITELIST=true bundle exec rake
fi

#3
title "CHECK RUBY"
bundle exec rubocop -D -S

#4
title "CHECK DNS"
bundle exec github-pages health-check

title "CLEANUP"
rm -Rf _site
