#!/usr/bin/env bash

set -e # halt script on error

title() {
  echo
  echo " --------------------------  $1"
  echo
}

script/branding

#1
title "CHECKING MARKDOWN"
script/remark

#2
title "CHECKING SITE"
if "$CI"; then
  # set JGT as an environment variable on travis-ci.org website
  # JEKYLL_GITHUB_TOKEN="$JGT" DISABLE_WHITELIST=true bundle exec rake
  DISABLE_WHITELIST=true bundle exec rake
else
  JEKYLL_GITHUB_TOKEN="$(cat ~/.token)" DISABLE_WHITELIST=true bundle exec rake
fi

#3
title "CHECKING RUBY"
bundle exec rubocop -D -S

#4
title "CHECKING DNS"
bundle exec github-pages health-check

title "CLEANING UP"
bundle exec jekyll clean
