#!/usr/bin/env bash

set -e # halt script on error

title() {
    echo
    echo " --------------------------  $1"
    echo
}

script/branding

#1
# title "checking markdown"
# script/remark

#2
title "CHECK SITE"
#JEKYLL_GITHUB_TOKEN="$(cat ~/.token)" DISABLE_WHITELIST=true bundle exec rake
JEKYLL_GITHUB_TOKEN="$(cat ~/.token)" bundle exec rake

#3
title "CHECK RUBY"
bundle exec rubocop -D -S

#4
title "CHECK DNS"
bundle exec github-pages health-check

title "CLEANUP"
rm -Rf _site


# msg() {
#     printf "\e[0;37m==> $1\e[0m\n"
# }

# INGORE_HREFS=$(ruby -e 'puts %w{
#   twitter.com
#   github.com\/keegoid
# }.map{|h| "/#{h}/"}.join(",")')

# msg "Building..."
# bundle exec jekyll build --trace

# msg "Proofing..."
# bundle exec htmlproof ./_site --url-ignore $INGORE_HREFS
