#!/usr/bin/env bash

set -e

if "$CI"; then
  # ./node_modules/.bin/remark --config-path .remarkrc --no-rc ./*.md ./*/**.md
  ./node_modules/.bin/remark --config-path .remarkrc ./*.md ./*/**.md
else
  # ./node_modules/.bin/remark --config-path .remarkrc --output --no-rc ./*.md ./*/**.md
  ./node_modules/.bin/remark --config-path .remarkrc --output ./*.md ./*/**.md
fi
