#!/usr/bin/env bash
# build site locally and run
# run this script from root of project

set -e

title() {
    echo
    echo " --------------------------  $1"
    echo
}

script/branding

# shellcheck disable=SC2155
export JEKYLL_GITHUB_TOKEN=$(cat ~/.token)

title "START SERVER"
#JEKYLL_GITHUB_TOKEN="$(cat ~/.token)" DISABLE_WHITELIST=true \
JEKYLL_GITHUB_TOKEN="$(cat ~/.token)" bundle exec jekyll serve -w --config _config.yml,_config_local.yml --drafts --incremental

title "CLEARNUP"
bundle exec jekyll clean
