#!/usr/bin/env bash
# build site locally and run

set -e

title() {
    echo
    echo " --------------------------  $1"
    echo
}

script/branding

# shellcheck disable=SC2155
export JEKYLL_GITHUB_TOKEN=$(cat ~/.token)

title "STARTING SERVER"
JEKYLL_GITHUB_TOKEN="$(cat ~/.token)" DISABLE_WHITELIST=true \
bundle exec jekyll serve --watch --config _config.yml,_config_local.yml --drafts --incremental

title "CLEANING UP"
bundle exec jekyll clean
